language: python
python:
  - 3.6
branches:
  only:
    - master
    - develop
notifications:
  email: false

addons:
  apt:
    packages:
      - sox

dist: trusty
sudo: true

before_install:
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - bash continuous-integration/travis/install.sh

# Install packages
install:
  - export PATH="$HOME/miniconda/miniconda/bin:$HOME/tools/autovot/autovot/bin:$PATH"
  - source activate test-environment
  - which python
  - conda list

# Run test
script:
  - travis_wait 120 coverage run --source=conch setup.py test

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/downloads
    - $HOME/tools
    - $HOME/miniconda
